name: CI
on: [push]

jobs:
  echidna:
    name: CI
    runs-on: ubuntu-latest
    # env:
    #   MNEMONIC: ${{ secrets.MNEMONIC }}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16

      - name: Install node dependencies
        run: npm install

      - name: Run contract test
        run:  npm run test
